# database public url.
db.url=${JDBC_DATABASE_URL}
# brevo api data.
brevo.url=https://api.brevo.com/v3/smtp/email
brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=${BREVO_SENDER_EMAIL}
brevo.sender.name=${BREVO_SENDER_NAME}

